[project]
name = "schema-mapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.0",
    "ipywidgets>=8.1.7",
    "langchain-openai>=0.3.28",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
]
